// frontend/src/shared/components/Header/FilterTab.tsx
"use client";
import { usePathname } from "next/navigation";
import { Icons } from "../Icons";
import { Swiper, SwiperSlide } from "swiper/react";
import { useSearchParams } from "next/navigation";
import Link from "next/link";
import { checkPath, setParams } from "../../utils";
import { categories } from "shared/enums";

export const FilterTab = () => {
  const pathname = usePathname();
  const path = checkPath(pathname);
  const searchParams = useSearchParams();
  const filter = (searchParams.get("filter") as string) || "";
  const swiperParams = {
    slidesPerView: 3.8,
    slidesOffsetAfter: 17,
    slidesOffsetBefore: 3,
    spaceBetween: 15,
    freeMode: true,
    breakpoints: {
      "360": {
        slidesPerView: 3.8,
        spaceBetween: 15,
      },
      "390": {
        slidesPerView: 3.6,
        spaceBetween: 15,
      },
      "430": {
        slidesPerView: 4.4,
        spaceBetween: 15,
      },
      "600": {
        slidesPerView: 5.4,
        spaceBetween: 15,
      },
      "700": {
        slidesPerView: 6.4,
        spaceBetween: 15,
      },
      "800": {
        slidesPerView: 7.4,
        spaceBetween: 15,
      },
      "900": {
        slidesPerView: 8.4,
        spaceBetween: 15,
      },
      "1000": {
        slidesPerView: 9.4,
        spaceBetween: 15,
      },
    },
  };
  if (path === "questions") {
    return (
      <div className="pb-5 max-w-[1000px] mx-auto pt-2">
        <Swiper {...swiperParams}>
          {categories.map(({ id, icon, title, subtitle }) => (
            <SwiperSlide key={id}>
              <Link
                href={setParams(searchParams, { filter: id })}
                className="grid justify-center text-center"
              >
                <Icons
                  variant={icon}
                  className={`text-7 ${
                    id === filter ? "text-base-content" : "text-base-300"
                  }`}
                  weight={id === filter ? "fill" : "duotone"}
                />
                <div
                  className={`font-semibold -mb-[4px] ${
                    id === filter ? "text-base-content" : "text-base-300"
                  }`}
                >
                  {title}
                </div>
                <div className={`text-3 font-semibold text-base-300`}>
                  {subtitle}
                </div>
              </Link>
            </SwiperSlide>
          ))}
        </Swiper>
      </div>
    );
  }
};

// frontend/src/components/FilterTab.svelte
<script>
	// @ts-nocheck
	import { onMount } from 'svelte';
	import Swiper from 'swiper';
	import { register } from 'swiper/element/bundle';
	import Icons from './Icons.svelte';
	import { items, switchFilter, filter } from '../stores/useHeader';
	register();
	onMount(() => {
		const swiperEl = document.querySelector('swiper-container');
		const swiperParams = {
			slidesPerView: 3.8,
			spaceBetween: 15,
			freeMode: true,
			breakpoints: {
				'360': {
					slidesPerView: 3.8,
					spaceBetween: 15
				},
				'390': {
					slidesPerView: 3.6,
					spaceBetween: 15
				},
				'430': {
					slidesPerView: 4.8,
					spaceBetween: 15
				}
			},
			on: {
				init() {
					// ...
				}
			}
		};

		// now we need to assign all parameters to Swiper element
		Object.assign(swiperEl, swiperParams);

		// and now initialize it
		swiperEl.initialize();
	});
	// register();
	// slides-per-view={3.8}
	// space-between={15}
	// freeMode={true}
	// breakpoints={{
	// 	'360': {
	// 		slidesPerView: 3.8,
	// 		spaceBetween: 15
	// 	},
	// 	'390': {
	// 		slidesPerView: 3.6,
	// 		spaceBetween: 15
	// 	},
	// 	'430': {
	// 		slidesPerView: 4.8,
	// 		spaceBetween: 15
	// 	}
	// }}
</script>

<div>
	<swiper-container init="false">
		{#each items as item (item)}
			<swiper-slide
				tabindex="0"
				role="button"
				on:keydown={() => switchFilter(item.id)}
				class="grid place-items-center"
				on:click={() => switchFilter(item.id)}
			>
				<Icons
					variant={item.icon}
					class={`text-7 ${item.id === $filter?.id ? 'fill-base-content' : 'fill-base-300'}`}
					weight={item.id === $filter?.id ? 'fill' : 'duotone'}
				/>
				<div
					class={`font-semibold -mb-[4px] ${
						item.id === $filter?.id ? 'text-base-content' : 'text-base-300'
					}`}
				>
					{item.title}
				</div>
				<div class={`text-3 font-semibold text-base-300`}>{item.subtitle}</div>
			</swiper-slide>
		{/each}
	</swiper-container>
</div>
