// frontend/src/app/(QuestionsFlow)/questions/page.tsx
"use client"
import { H } from "shared/utils"
import { Icons } from "../../../shared/components/Icons"
import { useQuestions } from "./page.hook"
import { PageContainer } from "shared/components/Containers"

export default function HomePage() {
  const { header, tabs, list } = useQuestions()
  return (
    <PageContainer>
      <Header {...header} />
      <Tabs {...tabs} />
      <List {...list} />
    </PageContainer>
  )
}
const Header = ({ item }: H<typeof useQuestions, "header">) => {
  return (
    <>
      {item ? (
        <div className="flex justify-between items-center px-4 h-16">
          <div className="flex gap-2 items-center">
            <div>
              <Icons
                variant={item.icon}
                className="fill-base-content text-8"
                weight="fill"
              />
            </div>
            <div className="">
              <div className="font-semibold text-4">{item.title}</div>
              <div className="font-semibold text-5 -mt-2 -mb-[3px]">Questions</div>
              <div className="font-semibold text-3 text-base-300">{item.subtitle}</div>
            </div>
          </div>
          <button className="btn btn-primary">Ask Question</button>
        </div>
      ) : (
        <div className="flex justify-between items-center px-4 h-16">
          <div className="font-semibold text-5">Top Questions</div>
          <button className="btn btn-primary">Ask Question</button>
        </div>
      )}
    </>
  )
}

const Tabs = ({ questionsViews }: H<typeof useQuestions, "tabs">) => (
  <div
    role="tablist"
    className="mt-6 rounded-none justify-center border-t border-b border-base-200 flex gap-4 h-12 items-center"
  >
    {questionsViews.map((item: any) => (
      <button
        key={item}
        className="text-base-300 font-bold"
      >
        {item}
      </button>
    ))}
  </div>
)

const List = ({
  isLoading,
  questions,
  item,
  items,
  isSuccess,
  isError,
  isEmpty
}: H<typeof useQuestions, "list">) => {
  if (isSuccess) {
    return (
      <div className="border-b border-base-200 bg-base-200/75">
        {!isLoading &&
          questions?.map(
            ({
              id,
              category,
              title,
              voteCount,
              answerCount,
              viewCount,
              user,
              timeAgo,
              approved
            }: any) => (
              <div
                key={id}
                className={`border-b border-base-300/50 last:border-base-200 pt-4 px-4 ${
                  item && "pb-4"
                }`}
              >
                <div className="flex items-center gap-2 font-medium text-base-300">
                  {approved && (
                    <Icons
                      variant="check-fat"
                      weight="fill"
                      className="text-4 text-success"
                    />
                  )}
                  <div
                    className={`${
                      approved
                        ? "text-success font-semibold"
                        : answerCount > 0
                        ? "text-base-content font-semibold"
                        : "text-base-300"
                    } `}
                  >
                    {answerCount !== 1 ? `${answerCount} answers` : `${answerCount} answer`}
                  </div>
                  <div className="w-1 h-1 bg-base-300 rounded-full" />
                  <div>{voteCount} votes</div>
                  <div className="w-1 h-1 bg-base-300 rounded-full" />
                  <div>{viewCount} views</div>
                </div>
                <div className="my-2 mb-3 font-medium">{title}</div>
                <div className="text-right flex justify-end items-center">
                  <div className="avatar">
                    <div className="w-5 h-5 rounded border-2 border-base-content mr-[6px]">
                      <img
                        src={user?.image}
                        alt="avatar"
                      />
                    </div>
                  </div>
                  <div className="flex gap-1 font-medium">
                    <div className="text-accent">{user?.username}</div>
                    <div className="text-base-300">answered {timeAgo}</div>
                  </div>
                </div>
                {!item && (
                  <div className="flex justify-end mb-4 mt-1">
                    <div className="flex w-fit text-base-300 font-medium">
                      <div className="flex gap-2 items-center">
                        <Icons
                          variant={items.find((x: any) => x.id === category)?.icon as string}
                          className="fill-base-content text-5"
                          weight="fill"
                        />
                        <div>{items.find((x: any) => x.id === category)?.title}</div>
                        <div>|</div>
                        <div>{items.find((x: any) => x.id === category)?.subtitle}</div>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            )
          )}
      </div>
    )
  }
  if (isLoading) {
    return (
      <div className="text-center text-base-300 pt-10">
        <span className="loading loading-infinity loading-lg"></span>
        <div className="font-semibold">Loading Questions</div>
      </div>
    )
  }
  if (isError) {
    return (
      <div className="text-center text-base-300 pt-10 px-10">
        <Icons
          variant="warning"
          weight="duotone"
          className="text-10"
        />
        <div className="font-semibold">
          We are sorry, an unexpected error occurred. Please refresh your browser or try again
          later.
        </div>
      </div>
    )
  }
  if (isEmpty) {
    return (
      <div className="text-center text-base-300 pt-10">
        <Icons
          variant="smiley-meh"
          weight="duotone"
          className="text-10"
        />
        <div className="font-semibold">No questions found</div>
      </div>
    )
  }
}

// frontend/src/routes/(questions)/questions/+page.svelte
<script>
	import { CheckFat } from 'phosphor-svelte';
	import Icons from '@components/Icons.svelte';
	import { filter } from '@stores/useHeader';
	import { questionsViews } from '@enums';
	// import { questions } from './page.specs';

	let questions = [
		{
			title: `As my little one begins to experience a wider range of emotions, what strategies or games could help them understand and express these feelings in a healthy, age-appropriate way?`,
			votes: 7,
			answers: 3,
			approved: true,
			views: 419,
			user: 'Antoni',
			userImage: 'https://daisyui.com/images/stock/photo-1534528741775-53994a69daeb.jpg',
			timeAgo: '2 min ago'
		},
		{
			title: `It's natural for young children to be scared of the unknown or everyday things. What can I do, or stories can I tell, to reassure them and reduce their fears during these startling moments?`,
			votes: 0,
			answers: 1,
			approved: false,
			views: 182,
			user: 'Michel Floyd',
			userImage: 'https://i.pravatar.cc/150?img=3',
			timeAgo: '53 min ago'
		},
		{
			title: `It's not uncommon to feel frustrated when dealing with the challenges of this age. How can I effectively manage my own feelings, so it doesn't impact my child negatively during these teaching moments?`,
			votes: 0,
			answers: 0,
			views: 92,
			user: 'Michel Floyd',
			userImage: 'https://i.pravatar.cc/150?img=3',
			timeAgo: '53 min ago'
		}
	];
</script>

{#if $filter}
	<div class="flex justify-between items-center px-4 h-16">
		<div class="flex gap-2 items-center">
			<div>
				<Icons variant={$filter?.icon} class="fill-base-content text-8" weight="fill" />
			</div>
			<div class="">
				<div class="font-semibold text-4">{$filter?.title}</div>
				<div class="font-semibold text-5 -mt-2 -mb-[3px]">Questions</div>
				<div class="font-semibold text-3 text-base-300">{$filter?.subtitle}</div>
			</div>
		</div>
		<button class="btn btn-primary">Ask Question</button>
	</div>
{:else}
	<div class="flex justify-between items-center px-4 h-16">
		<div class="font-semibold text-5">Top Questions</div>
		<button class="btn btn-primary">Ask Question</button>
	</div>
{/if}

<div
	role="tablist"
	class="mt-6 rounded-none justify-center border-t border-base-200 flex gap-4 h-12 items-center"
>
	{#each questionsViews as item}
		<button class="text-base-300 font-bold">{item}</button>
	{/each}
</div>

<div class="border-b border-base-300 bg-base-200">
	{#each questions as { title, votes, answers, views, userImage, user, timeAgo, approved }}
		<div class="border-t border-base-300 p-4">
			<div class="flex items-center gap-2 font-medium text-base-300">
				{#if approved}
					<CheckFat class="fill-success text-4" weight="fill" />
				{/if}
				<div
					class={`${
						approved
							? 'text-success font-semibold'
							: answers > 0
							? 'text-base-content font-semibold'
							: 'text-base-300'
					} `}
				>
					{answers}
					{answers !== 1 ? 'answers' : 'answer'}
				</div>
				<div class="w-1 h-1 bg-base-300 rounded-full" />
				<div>{votes} votes</div>
				<div class="w-1 h-1 bg-base-300 rounded-full" />
				<div>{views} views</div>
			</div>
			<div class="my-2 font-medium">{title}</div>
			<div class="text-right flex justify-end items-center">
				<div class="avatar">
					<div class="w-5 h-5 rounded border-2 border-base-content mr-[6px]">
						<img src={userImage} alt="avatar" />
					</div>
				</div>
				<div class="flex gap-1 font-medium">
					<div class="text-accent">{user}</div>
					<div class="text-base-300">answered {timeAgo}</div>
				</div>
			</div>
		</div>
	{/each}
</div>
